version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    networks:
      - minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: $LOGIN
      MINIO_ROOT_PASSWORD: $PASSWORD
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_DOMAIN: $DOMAIN
    command: server /data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_storage:/etc/nginx/nginx.conf
    networks:
      - minio

networks:
  minio:
    driver: "bridge"

volumes:
  minio_storage:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/minio'

  nginx_storage:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: './nginx.conf'
